# Site settings
title: BiG-SCAPE CORASON
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  August 2023
baseurl: /bigscape-corason
url: "http://localhost:4000"
github: [metadata]
include:
  - _static

twitter_username: nselem35
github_username:  nselem

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
